### ISSUE TITLE
Создать таблицу services услуги

### ISSUE THREAD

**Issue by 3xEm3** [cancerogen16/canna#13]
id (int): primary key,
name (char 256): название услуги,
description (text): описание услуги только текст,
photo (char 256): url к фото
duration (int):  количество минут для записи,
price (dec): цена
category_id: к какой категории услуг относится

**Comment by cancerogen16** [comment]
Schema::create('services', function (Blueprint $table) {
            $table->id();

            $table->foreignId('category_id') // привязка к категории
                ->constrained('categories')
                ->cascadeOnDelete();

            $table->foreignId('master_id') // привязка мастера к услуге
            ->constrained('masters')
                ->cascadeOnDelete();

            $table->foreignId('salon_id') // привязка к салону
            ->constrained('salons')
                ->cascadeOnDelete();

            $table->string('title', 191); // название
            $table->string('slug', 191)->unique(); // ярлык

            $table->decimal('price', 8, 0); // цена услуги
            $table->string('duration')->default(1); // количество минут для записи

            $table->string('use_break')->nullable(); // Перерыв после записи

            $table->string('image', 255)->nullable(); // изображение услуги

            $table->text('excerpt')->nullable(); // краткое описание
            $table->text('description')->nullable(); // описание

            $table->timestamps(); // created_at and updated_at
            $table->softDeletes();
        });
