### ISSUE TITLE
Добавить время окончания рабочего дня

### ISSUE THREAD

**Issue by cancerogen16** [cancerogen16/canna#133]
В календаре должно быть время начала и конца рабочего дня

**Comment by ruskiiamov** [comment]
Это же первый и последний слот для одного дня. Зачем отдельные поля?

**Comment by cancerogen16** [comment]
Что значит, последний слот?

**Comment by ruskiiamov** [comment]
В таблице calendars хранятся данные в виде:
мастер c master_id работает в час, который начинается в start_datetime, по записи date_id.
В итоге для одного дня из 8 рабочих часов у мастера будет 8 таких строк.
Например как у нас сейчас в сидере:
![Screenshot from 2021-08-02 23-53-47](https://user-images.githubusercontent.com/75389846/127922612-674daf8a-29d9-4a76-a5c9-2c67d3c591b8.png)
Из таблицы у мастера 1: 
3-го авгута 9 рабочих часов. Первый начинается в 6 утра. Последний начинается в 14 часов. То есть рабочий день с 6 до 15. Из них с 6 до 8 уже заняты записью 1. Остальные часы свободны. Как-то так

**Comment by cancerogen16** [comment]
Получается, что за один запрос формируется только один слот? Значит, во-первых фронту надо будет создать блок, где видны все часы рабочего дня и они должны отправлять запрос на запись в базу и менять свое состояние при нажатии. Во-вторых, менеджеру придётся для каждого дня много раз выбирать часы работы. Это мы упростили до слота, величиной в час. А если сделать слот полчаса или, не дай бог, 15 минут, то менеджер с ума сойдёт тыкать. 
Я за вариант DIKIDI. Можно сделать выбор даты, сначала просто из селекта и два селекта, начало work_from и конец рабочего дня work_to. Можно пока без перерывов. В контроллер придёт два числа, начало и конец и надо будет из них сформировать нужные слоты. Это всё за один запрос.

**Comment by cancerogen16** [comment]
Судя по этой таблице у мастера 1 заняты 3 часа с 6 до 9

**Comment by ruskiiamov** [comment]
Да, с  6 до 9, правильно. Я имел в виду до 8 включительно) 
Я абсолютно согласен, что руками менеджеру протыкивать каждый слот не надо. Нужна автоматизация. Будем делать на стороне фронта или бэка - давайте  договоримся. Если делать на стороне фронта, то можно более гибко настриваь график, например убрать какие-то часы и т. д. Для начала можно как ты написал. Тогда нужен отельный роут с экшеном.

**Comment by cancerogen16** [comment]
Роут не нужен. Просто в контроллере обработать и всё. 
Более гибко настраивать график необязательно. На дикиди можно задать один перерыв в течение рабочего дня и им хватает.

**Comment by cancerogen16** [comment]
А со фронтом будут проблемы. Антон всего один и он вряд ли успеет. Там основной работы ещё много

**Comment by ruskiiamov** [comment]
Хорошо. Давай так. Тогда в запросе нужно указать ещё диапазон дней или на каждый день отдельный запрос? И если диапазон, то выходные ещё надо указать

**Comment by cancerogen16** [comment]
На дикиди с формы отправляется начало и конец рабочего дня и массив дней, на которые это распространяется

**Comment by cancerogen16** [comment]
Можно пока делать для одного дня. Но если фронт сможет сделать выбор нескольких дней, то можно и несколько
