### ISSUE TITLE
Надо решить кто будет создавать услуги. Только админ или мастера смогут сами добавлять свои.

### ISSUE THREAD

**Issue by ruskiiamov** [cancerogen16/canna#23]
я предлагаю так:
услуги создают мастера, но в определенных категориях услуг, которые создает админ

**Comment by ruslan-kiiamov** [comment]
я предлагаю так:
услуги создают мастера, но в определенных категориях услуг, которые создает админ

**Comment by cancerogen16** [comment]
Решаем, что услуги добавляют админ и салоны?

**Comment by ruskiiamov** [comment]
Услуги создают салоны и привязывают их к категории и мастеру.
Категории создает админ.
Я так понял, что остановилсь на этом. 
Закрываем issue?

**Comment by Margo-Margo** [comment]
да, всё так. закрываю.
