### ISSUE TITLE
Определиться с иерархией услуг.

### ISSUE THREAD

**Issue by ruskiiamov** [cancerogen16/canna#24]
Первый уровень: категория услуг. Таблица categories. Категории: массаж, уход за лицом,  косметические процедуры, красота.
Второй уровень: сама услуга. Таблица services. Например, маникюр, шугаринг и т.п. Маникюр бывает разный, но для упрощения можно считать, что вид маникюра клиент выбирает на месте при получении услуги. Или придется добавлять ещё один уровень. Можно добавить опции, как в товарах. Тогда добавить таблицу options. Тут есть нюанс. В магазинах опции общие. Тогда в админке, при создании услуги придется ввести поиск опции, т.к. их может быть много. Или при создании опции указать к какой услуге или категории она относится и можно будет выбирать из списка. Или заранее опции не создавать, а в настройки услуги ввести возможность добавления опций. Тогда для каждой услуги опции будут свои.

**Comment by ruskiiamov** [comment]
если сделать сам маникюр категорией, то не нужно создавать опции

**Comment by cancerogen16** [comment]
Просто услуга может не иметь разновидностей. И получается, что услуга у нас, это категория.

**Comment by ruskiiamov** [comment]
Я предлагаю создать 15-20 категорий, в которых мастера уже сами будут создавать свои конкретные услуги. 
Если например категория маникюр слишком обширная, то можно разбить ее на несколько (2 или 3). Получится:
Маникюр - вариант 1
Маникюр - вариант 2

**Comment by cancerogen16** [comment]
Категории ещё надо сгруппировать. массаж, уход за лицом, косметические процедуры, красота и т.п.

**Comment by ruskiiamov** [comment]
Решено пока делать без опций
